name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install uv
      run: pip install uv
    
    - name: Check if lockfile is up to date
      run: |
        uv sync --frozen --dev --dry-run
    
    - name: Install dependencies
      run: uv sync --frozen --dev
    
    - name: Format check with ruff
      run: uv run ruff format --check .
    
    - name: Lint with ruff
      run: uv run ruff check .
    
    - name: Run tests
      run: uv run pytest -v

  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t personal-website .
    
    - name: Test Docker container
      run: |
        docker run -d --name test-container -p 8000:8000 personal-website
        sleep 10
        curl -f http://localhost:8000/healthz || exit 1
        docker stop test-container
        docker rm test-container